# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := uv_dtrace_header
### Rules for final target.
$(obj).target/http-server/libuv/uv_dtrace_header.stamp: TOOLSET := $(TOOLSET)
$(obj).target/http-server/libuv/uv_dtrace_header.stamp:  FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/http-server/libuv/uv_dtrace_header.stamp
# Add target alias
.PHONY: uv_dtrace_header
uv_dtrace_header: $(obj).target/http-server/libuv/uv_dtrace_header.stamp

