# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := http_server
DEFS_Debug := \
	'-D_LARGEFILE_SOURCE' \
	'-D_FILE_OFFSET_BITS=64' \
	'-D_POSIX_C_SOURCE=200112' \
	'-DHTTP_PARSER_STRICT=0' \
	'-DDEBUG' \
	'-D_DEBUG' \
	'-DEV_VERIFY=2'

# Flags passed to all source files.
CFLAGS_Debug := \
	-Wall \
	-ansi \
	-pthread \
	-fvisibility=hidden \
	-g \
	-O0 \
	-fwrapv

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-exceptions \
	-std=c++11

INCS_Debug := \
	-Ihttp-server/libuv/include \
	-Ihttp-server/http-parser

DEFS_Release := \
	'-D_LARGEFILE_SOURCE' \
	'-D_FILE_OFFSET_BITS=64' \
	'-D_POSIX_C_SOURCE=200112' \
	'-DHTTP_PARSER_STRICT=0' \
	'-DNDEBUG'

# Flags passed to all source files.
CFLAGS_Release := \
	-Wall \
	-ansi \
	-pthread \
	-fvisibility=hidden \
	-O3 \
	-fstrict-aliasing \
	-fomit-frame-pointer \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-exceptions \
	-std=c++11

INCS_Release := \
	-Ihttp-server/libuv/include \
	-Ihttp-server/http-parser

OBJS := \
	$(obj).target/$(TARGET)/http-server/simple_http.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-pthread

LDFLAGS_Release := \
	-pthread

LIBS :=

$(obj).target/http-server/libhttp_server.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/http-server/libhttp_server.a: LIBS := $(LIBS)
$(obj).target/http-server/libhttp_server.a: TOOLSET := $(TOOLSET)
$(obj).target/http-server/libhttp_server.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/http-server/libhttp_server.a
# Add target alias
.PHONY: http_server
http_server: $(obj).target/http-server/libhttp_server.a

# Add target alias to "all" target.
.PHONY: all
all: http_server

# Add target alias
.PHONY: http_server
http_server: $(builddir)/libhttp_server.a

# Copy this to the static library output path.
$(builddir)/libhttp_server.a: TOOLSET := $(TOOLSET)
$(builddir)/libhttp_server.a: $(obj).target/http-server/libhttp_server.a FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/libhttp_server.a
# Short alias for building this static library.
.PHONY: libhttp_server.a
libhttp_server.a: $(obj).target/http-server/libhttp_server.a $(builddir)/libhttp_server.a

# Add static library to "all" target.
.PHONY: all
all: $(builddir)/libhttp_server.a

